// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Script } from "forge-std/Script.sol";
import { console2 } from "forge-std/console2.sol";

contract Export is Script {
    function run() external {
        string memory network = vm.envOr("DEPLOYMENT_NETWORK", string("arbitrum-sepolia"));
        string memory deploymentPath = string.concat("deployments/", network, ".json");

        string memory json = vm.readFile(deploymentPath);

        uint256 chainId = vm.parseJsonUint(json, ".chainId");
        address treeRegistry = vm.parseJsonAddress(json, ".TreeRegistry");
        address treeNFT = vm.parseJsonAddress(json, ".TreeNFT");
        address treeBond = vm.parseJsonAddress(json, ".TreeBond");
        address verificationRegistry = vm.parseJsonAddress(json, ".VerificationRegistry");

        string memory output = string.concat(
            "// Auto-generated by script/Export.s.sol. Do not edit manually.\n",
            "// Run `make export` in treebondai-smartcontract to refresh.\n",
            "export const CHAIN_ID = ",
            vm.toString(chainId),
            " as const;\n\n",
            "export const CONTRACTS = {\n",
            "  treeRegistry: \"",
            vm.toString(treeRegistry),
            "\",\n",
            "  treeNFT: \"",
            vm.toString(treeNFT),
            "\",\n",
            "  treeBond: \"",
            vm.toString(treeBond),
            "\",\n",
            "  verificationRegistry: \"",
            vm.toString(verificationRegistry),
            "\",\n",
            "} as const;\n"
        );

        vm.writeFile("exports/addresses.ts", output);
        vm.writeFile("exports/addresses.json", json);

        console2.log("Exported addresses for", network);
        console2.log("TreeRegistry:", treeRegistry);
        console2.log("TreeNFT:", treeNFT);
        console2.log("TreeBond:", treeBond);
        console2.log("VerificationRegistry:", verificationRegistry);
    }
}
